(*
  Copyright 2025, MARS-Curiosity - REST Library

  Home: https://github.com/andrea-magni/MARS
*)

unit Server.Database;

interface

uses
  MARS.Utils.Parameters
;

type
  /// <summary> Creates the CUSTOMERS table of the demo, with a few rows, when it does not exist.
  /// The database is a Firebird file (see FireDAC.MAIN_DB.Database in Server.ini): FireDAC
  /// creates it when it is missing (OpenMode=OpenOrCreate) </summary>
  TDemoDatabase = class
  public
    /// <summary> Before the connection definitions are loaded: {bin} in the file name of the
    /// database becomes the folder of the server </summary>
    class procedure Prepare(const AParameters: TMARSParameters);
    class procedure Setup(const AConnectionDefName: string);
  end;

implementation

uses
  System.SysUtils, System.Rtti
, FireDAC.Comp.Client
, FireDAC.Phys.FB // the FireDAC driver of the database (DriverID in Server.ini)
, MARS.Data.FireDAC
;

const
  DATABASE_PARAM = 'FireDAC.MAIN_DB.Database';

class procedure TDemoDatabase.Prepare(const AParameters: TMARSParameters);
var
  LBinFolder: string;
begin
  LBinFolder := ExcludeTrailingPathDelimiter(ExtractFilePath(GetModuleName(HInstance)));
  AParameters.Values[DATABASE_PARAM] :=
    AParameters.ByName(DATABASE_PARAM, '').AsString.Replace('{bin}', LBinFolder, [rfIgnoreCase]);
end;

class procedure TDemoDatabase.Setup(const AConnectionDefName: string);
var
  LFD: TMARSFireDAC;
  LTableExists: Boolean;
begin
  // no activation here: TMARSFireDAC works without one, as long as the statements do not use
  // PathParam_*, QueryParam_*, Token_* and the like
  LFD := TMARSFireDAC.Create(AConnectionDefName);
  try
    LTableExists := False;
    LFD.Query('select count(*) from rdb$relations where rdb$relation_name = ''CUSTOMERS''', nil, nil,
      procedure (AQuery: TFDQuery)
      begin
        LTableExists := AQuery.Fields[0].AsInteger > 0;
      end
    );
    if LTableExists then
      Exit;

    // the table first, then its rows: a transaction for each
    LFD.InTransaction(
      procedure (ATransaction: TFDTransaction)
      begin
        LFD.ExecuteSQL(
            'create table customers ('
          + '  id integer generated by default as identity primary key,'
          + '  name varchar(100) not null,'
          + '  city varchar(50),'
          + '  credit numeric(12,2) default 0 not null'
          + ')', ATransaction);
      end
    );
    LFD.InTransaction(
      procedure (ATransaction: TFDTransaction)
      const
        CUSTOMERS: array[0..5] of string = (
          '''Ada Lovelace'', ''London'', 1500', '''Alan Turing'', ''London'', 800'
        , '''Grace Hopper'', ''New York'', 2300', '''Niklaus Wirth'', ''Zurich'', 1200'
        , '''Anders Hejlsberg'', ''Copenhagen'', 3100', '''Edsger Dijkstra'', ''Amsterdam'', 950'
        );
      var
        LValues: string;
      begin
        for LValues in CUSTOMERS do
          LFD.ExecuteSQL('insert into customers (name, city, credit) values (' + LValues + ')', ATransaction);
      end
    );
  finally
    LFD.Free;
  end;
end;

end.
