[DefaultEngine]
;BasePath=/rest
;Port=8080
ThreadPoolSize=100

;DefaultApp.JWT.Issuer=MARS-Curiosity
;DefaultApp.JWT.Secret={788A2FD0-8E93-4C11-B5AF-51867CF26EE7}
;DefaultApp.JWT.Duration=1

FireDAC.MAIN_DB.DriverID=SQLite
FireDAC.MAIN_DB.Database=.\MCPDemoDatabase.s3db
