[DefaultEngine]
;BasePath=/rest
;Port=8080
ThreadPoolSize=100

;DefaultApp.JWT.Issuer=MARS-Curiosity
;DefaultApp.JWT.Secret=
;DefaultApp.JWT.Duration=1

FireDAC.MAIN_DB.DriverID=SQLite
FireDAC.MAIN_DB.Database=.\MCPDemoDatabase.s3db
