/******************** TABLES **********************/

CREATE TABLE CUSTOMER
(
  ID       INTEGER      NOT NULL IDENTITY(1,1),
  [NAME]   VARCHAR(250) NOT NULL,
  VAT_ID   VARCHAR(30),
  COUNTRY  VARCHAR(10),
  CONSTRAINT INTEG_17 PRIMARY KEY (ID)
);

CREATE TABLE INVOICE
(
  ID           INTEGER        NOT NULL IDENTITY(1,1),
  INVOICE_DATE DATE           NOT NULL,
  INVOICE_NUM  INTEGER        NOT NULL,
  CUSTOMER_ID  INTEGER        NOT NULL,
  AMOUNT       NUMERIC(15,4)  DEFAULT 0,
  CONSTRAINT INTEG_12 PRIMARY KEY (ID)
);

CREATE TABLE ROLES
(
  ID          INTEGER      NOT NULL IDENTITY(1,1),
  [NAME]      VARCHAR(100),
  DESCRIPTION VARCHAR(250),
  CONSTRAINT PK_ROLES_0 PRIMARY KEY (ID)
);

CREATE TABLE USERS
(
  ID            INTEGER      NOT NULL IDENTITY(1,1),
  USERNAME      VARCHAR(250) NOT NULL,
  PASSWORD_HASH VARCHAR(250),
  IS_ACTIVE     SMALLINT,
  REALNAME      VARCHAR(250),
  LANG          VARCHAR(20),
  OTP_SECRET VARCHAR(250) NULL,
  CONSTRAINT INTEG_2 PRIMARY KEY CLUSTERED (ID)
);

CREATE TABLE USERS_CUSTOMERS
(
  USER_ID     INTEGER NOT NULL,
  CUSTOMER_ID INTEGER NOT NULL
);

CREATE TABLE USERS_ROLES
(
  ID         INTEGER   NOT NULL IDENTITY(1,1),
  USER_ID    INTEGER   NOT NULL,
  ROLE_ID    INTEGER   NOT NULL,
  START_DATE DATETIME2,
  END_DATE   DATETIME2,
  CONSTRAINT INTEG_8 PRIMARY KEY (ID)
);
GO

/********************* FOREIGN KEYS **********************/

ALTER TABLE INVOICE ADD CONSTRAINT FK_INVOICE_CUSTOMER
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID)
  ON UPDATE CASCADE;
GO
