(*
  Copyright 2025, MARS-Curiosity - REST Library

  Home: https://github.com/andrea-magni/MARS
*)

unit Server.Database;

interface

uses
  MARS.Utils.Parameters
;

type
  /// <summary> Creates the database of the demo (a file, see IBDAC.MAIN_DB.Database in
  /// Server.ini) and its CUSTOMERS table, with a few rows, when they do not exist </summary>
  TDemoDatabase = class
  public
    /// <summary> Before the connection definitions are loaded: {bin} in the file name of the
    /// database becomes the folder of the server </summary>
    class procedure Prepare(const AParameters: TMARSParameters);
    class procedure Setup(const AConnectionDefName: string);
  end;

implementation

uses
  System.SysUtils, System.Rtti
, IBC
, MARS.Data.IBDAC
;

const
  DATABASE_PARAM = 'IBDAC.MAIN_DB.Database';

class procedure TDemoDatabase.Prepare(const AParameters: TMARSParameters);
var
  LBinFolder: string;
begin
  LBinFolder := ExcludeTrailingPathDelimiter(ExtractFilePath(GetModuleName(HInstance)));
  AParameters.Values[DATABASE_PARAM] :=
    AParameters.ByName(DATABASE_PARAM, '').AsString.Replace('{bin}', LBinFolder, [rfIgnoreCase]);
end;

class procedure TDemoDatabase.Setup(const AConnectionDefName: string);
var
  LConnection: TIBCConnection;
  LIBDAC: TMARSIBDAC;
  LTableExists: Boolean;
begin
  // the database file, on a local server
  LConnection := TMARSIBDAC.CreateConnectionByDefName(AConnectionDefName);
  try
    if (SameText(LConnection.Server, 'localhost') or (LConnection.Server = '127.0.0.1'))
      and not FileExists(LConnection.Database) then
    begin
      LConnection.Params.Add(Format('USER ''%s''', [LConnection.Username]));
      LConnection.Params.Add(Format('PASSWORD ''%s''', [LConnection.Password]));
      LConnection.Params.Add('DEFAULT CHARACTER SET UTF8');
      LConnection.CreateDatabase;
    end;
  finally
    LConnection.Free;
  end;

  // no activation here: TMARSIBDAC works without one, as long as the statements do not use
  // PathParam_*, QueryParam_*, Token_* and the like
  LIBDAC := TMARSIBDAC.Create(AConnectionDefName);
  try
    LTableExists := False;
    LIBDAC.Query('select count(*) from rdb$relations where rdb$relation_name = ''CUSTOMERS''', nil, nil,
      procedure (AQuery: TIBCQuery)
      begin
        LTableExists := AQuery.Fields[0].AsInteger > 0;
      end
    );
    if LTableExists then
      Exit;

    // two explicit transactions: with the default one (autocommit, commit retaining) the
    // inserts would not see the new table
    LIBDAC.InTransaction(
      procedure (ATransaction: TIBCTransaction)
      begin
        LIBDAC.ExecuteSQL(
            'create table customers ('
          + '  id integer generated by default as identity primary key,'
          + '  name varchar(100) not null,'
          + '  city varchar(50),'
          + '  credit numeric(12,2) default 0 not null'
          + ')', ATransaction);
      end
    );
    LIBDAC.InTransaction(
      procedure (ATransaction: TIBCTransaction)
      const
        CUSTOMERS: array[0..5] of string = (
          '''Ada Lovelace'', ''London'', 1500', '''Alan Turing'', ''London'', 800'
        , '''Grace Hopper'', ''New York'', 2300', '''Niklaus Wirth'', ''Zurich'', 1200'
        , '''Anders Hejlsberg'', ''Copenhagen'', 3100', '''Edsger Dijkstra'', ''Amsterdam'', 950'
        );
      var
        LValues: string;
      begin
        for LValues in CUSTOMERS do
          LIBDAC.ExecuteSQL('insert into customers (name, city, credit) values (' + LValues + ')', ATransaction);
      end
    );
  finally
    LIBDAC.Free;
  end;
end;

end.
