{$if compilerversion = 22}
  {$define DelphiXE}
{$ifend}

{$if compilerversion = 23}
  {$define DelphiXE2}
{$ifend}

{$if compilerversion = 24}
  {$define DelphiXE3}
{$ifend}

{$if compilerversion = 25}
  {$define DelphiXE4}
{$ifend}

{$if compilerversion = 26}
  {$define DelphiXE5}
{$ifend}

{$if compilerversion = 27}
  {$define DelphiXE6}
{$ifend}

{$if compilerversion = 28}
  {$define DelphiXE7}
{$ifend}

{$if compilerversion = 29}
  {$define DelphiXE8}
{$ifend}

{$if compilerversion = 30}
  {$define Delphi10Seattle}
{$ifend}

{$if compilerversion = 31}
  {$define Delphi10Berlin}
{$ifend}

{$if compilerversion = 32}
  {$define Delphi10Tokyo}
{$ifend}

{$if compilerversion >= 22}
  {$define DelphiXE_UP}
{$ifend}

{$if compilerversion >= 23}
  {$define DelphiXE_UP}
  {$define DelphiXE2_UP}
{$ifend}

{$if compilerversion >= 24}
  {$define DelphiXE_UP}
  {$define DelphiXE2_UP}
  {$define DelphiXE3_UP}
{$ifend}

{$if compilerversion >= 25}
  {$define DelphiXE_UP}
  {$define DelphiXE2_UP}
  {$define DelphiXE3_UP}
  {$define DelphiXE4_UP}
{$ifend}

{$if compilerversion >= 26}
  {$define DelphiXE_UP}
  {$define DelphiXE2_UP}
  {$define DelphiXE3_UP}
  {$define DelphiXE4_UP}
  {$define DelphiXE5_UP}
{$ifend}

{$if compilerversion >= 27}
  {$define DelphiXE_UP}
  {$define DelphiXE2_UP}
  {$define DelphiXE3_UP}
  {$define DelphiXE4_UP}
  {$define DelphiXE5_UP}
  {$define DelphiXE6_UP}
{$ifend}

{$if compilerversion >= 28}
  {$define DelphiXE_UP}
  {$define DelphiXE2_UP}
  {$define DelphiXE3_UP}
  {$define DelphiXE4_UP}
  {$define DelphiXE5_UP}
  {$define DelphiXE6_UP}
  {$define DelphiXE7_UP}
{$ifend}

{$if compilerversion >= 29}
  {$define DelphiXE_UP}
  {$define DelphiXE2_UP}
  {$define DelphiXE3_UP}
  {$define DelphiXE4_UP}
  {$define DelphiXE5_UP}
  {$define DelphiXE6_UP}
  {$define DelphiXE7_UP}
  {$define DelphiXE8_UP}
{$ifend}

{$if compilerversion >= 30}
  {$define DelphiXE_UP}
  {$define DelphiXE2_UP}
  {$define DelphiXE3_UP}
  {$define DelphiXE4_UP}
  {$define DelphiXE5_UP}
  {$define DelphiXE6_UP}
  {$define DelphiXE7_UP}
  {$define DelphiXE8_UP}
  {$define Delphi10Seattle_UP}
{$ifend}

{$if compilerversion >= 31}
  {$define DelphiXE_UP}
  {$define DelphiXE2_UP}
  {$define DelphiXE3_UP}
  {$define DelphiXE4_UP}
  {$define DelphiXE5_UP}
  {$define DelphiXE6_UP}
  {$define DelphiXE7_UP}
  {$define DelphiXE8_UP}
  {$define Delphi10Seattle_UP}
  {$define Delphi10Berlin_UP}
{$ifend}

{$if compilerversion >= 32}
  {$define DelphiXE_UP}
  {$define DelphiXE2_UP}
  {$define DelphiXE3_UP}
  {$define DelphiXE4_UP}
  {$define DelphiXE5_UP}
  {$define DelphiXE6_UP}
  {$define DelphiXE7_UP}
  {$define DelphiXE8_UP}
  {$define Delphi10Seattle_UP}
  {$define Delphi10Berlin_UP}
  {$define Delphi10Tokyo_UP}  
{$ifend}
